### ISSUE TITLE
Разработка в команде REST API "Пользователи и роли"

### ISSUE THREAD

**Issue by alenapoliakova** [central-university-dev/2023-autumn-ab-python-hw-14-team-dev-alenapoliakova#1]
# Задание

1. Разбивка на команды (2-3 человека: @alenapoliakova и @gelycot).
2. Состав проекта:
   - [ ] REST API. Выбрали FastAPI, проект "Пользователи и роли" #7 
   - [ ] БД. Выбрали Postgres #2 #3
   - [ ] Tests (также тесты должны проверяться на тестовой БД)
   - [ ] Poetry #4
   - [ ] Docker #5
   - [ ] Type hints (пишем код с type hints, mypy должен проходить)
   - [ ] Linters (можно ruff)
   - [ ] Github Actions pipeline #6 
3. Распределение ролей в команде и создание backlog'a задач.
4. Работа над заданиями в соответствии с ролями и ответственностями.
5. Применение практик совместной работы:
   - создание веток в репозитории
   - pull requests
   - code review
   - bug fixing
   - рефакторинг
6. Ретроспектива и обсуждение:
   - Что получилось хорошо?
   - Где возникли сложности?
   - Как совместную работу можно улучшить?

## Критерии успеха:

- Учтено всё, что описано выше (в первую очередь из пункта 2)
- Работающий API сервис с основным функционалом.
- Приложение должно быть упаковано в Docker контейнер для легкого развертывания.
- Использование poetry для управления зависимостями.
- Отсутствие ошибок линтера ruff.
- Написание документации к API (описание эндпоинтов, методов и форматов данных).
- Наличие автоматических тестов, покрывающих основную функциональность.
- Покрытие тестами не менее 80%.

**Comment by gelycot** [comment]
Привет
